# install.packages('ks', repos='https://cloud.r-project.org/')
# install.packages('rgl', repos='https://cloud.r-project.org/')
# install.packages('misc3d', repos='https://cloud.r-project.org/')
# install.packages('readxl', repos='https://cloud.r-project.org/')
# install.packages('dplyr', repos='https://cloud.r-project.org/')
# install.packages('htmlwidgets', repos='https://cloud.r-project.org/')
# install.packages('ggplot2', repos='https://cloud.r-project.org/')
# install.packages('pandoc', repos='https://cloud.r-project.org/')
# install.packages('rjson', repos='https://cloud.r-project.org/')

install.packages('shiny', repos='https://cloud.r-project.org/')
install.packages('readxl', repos='https://cloud.r-project.org/')
install.packages('ks', repos='https://cloud.r-project.org/')
install.packages('rgl', repos='https://cloud.r-project.org/')
install.packages('misc3d', repos='https://cloud.r-project.org/')
install.packages('dpylr', repos='https://cloud.r-project.org/')
install.packages('htmlwidgets', repos='https://cloud.r-project.org/')
install.packages('ggplot2', repos='https://cloud.r-project.org/')
install.packages('pandoc', repos='https://cloud.r-project.org/')
install.packages('rjson', repos='https://cloud.r-project.org/')
install.packages('shinyFiles', repos='https://cloud.r-project.org/')
install.packages('zip', repos='https://cloud.r-project.org/')
install.packages('shinyWidgets', repos='https://cloud.r-project.org/')

# library(shiny)
# library(readxl)
# library (ks)
# library (rgl)
# library (misc3d)
# library (dplyr)
# library (htmlwidgets)
# library(ggplot2)
# library(pandoc)
# library(rjson)  
# library(shinyFiles)
# library(zip)
# library(shinyWidgets)